In [1]:
import pandas as pd

#### CSV files, with custom delimiter

In [2]:
df = pd.read_csv('data/survey_results_public.csv', index_col='Respondent')
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col='Column')

In [3]:
bd_df = df[df['Country']=='Bangladesh']

In [5]:
bd_df.to_csv('data/bangladesh.csv', sep='\t')

#### Excel file
**You need to have installed**
* xlwt to write to older xls format
* xlrd to read from older xls format
* openpyxl to read and write newer xlsx format

In [6]:
bd_df.to_excel('data/bangladesh.xlsx')

In [7]:
df_from_xl = pd.read_excel('data/bangladesh.xlsx', index_col='Respondent')

In [10]:
df_from_xl.head()

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
575,I am a developer by profession,Yes,19.0,19,NaN,NaN,NaN,Bangladesh,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET;ASP.NET Core,Angular;ASP.NET;ASP.NET Core,Somewhat more welcome now than last year,NaN,2,NaN
614,I am a developer by profession,Yes,NaN,18,NaN,NaN,NaN,Bangladesh,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,Django;Express;React.js;Vue.js,Express;jQuery;React.js;Vue.js,NaN,NaN,4,NaN
747,I am a student who is learning to code,Yes,21.0,15,NaN,NaN,NaN,Bangladesh,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Django;Laravel;React.js;Vue.js,NaN,Just as welcome now as I felt last year,NaN,4,NaN
916,I am a developer by profession,Yes,33.0,24,Monthly,40000.0,5652.0,Bangladesh,Bangladeshi taka,BDT,...,Difficult,Too long,No,Mathematics or statistics,Django;Drupal,Angular;Angular.js;Express;jQuery;Laravel;Reac...,Somewhat more welcome now than last year,40.0,5,3
945,I am a developer by profession,Yes,31.0,24,Monthly,70000.0,9888.0,Bangladesh,Bangladeshi taka,BDT,...,Neither easy nor difficult,Too long,No,"Another engineering discipline (such as civil,...",Express;React.js,Vue.js,Somewhat less welcome now than last year,30.0,4,4

In [11]:
df_from_xl.to_json('data/bangladesh.json')